package dev.abelab.hack.dena.db.mapper.base;

import dev.abelab.hack.dena.db.entity.TripPlanTagging;
import dev.abelab.hack.dena.db.entity.TripPlanTaggingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TripPlanTaggingBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    long countByExample(TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int deleteByExample(TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("tripPlanId") Integer tripPlanId, @Param("tagId") Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int insert(TripPlanTagging record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int insertSelective(TripPlanTagging record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    List<TripPlanTagging> selectByExample(TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TripPlanTagging record, @Param("example") TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TripPlanTagging record, @Param("example") TripPlanTaggingExample example);
}