package dev.abelab.hack.dena.db.mapper.base;

import dev.abelab.hack.dena.db.entity.TripPlan;
import dev.abelab.hack.dena.db.entity.TripPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TripPlanBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    long countByExample(TripPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int deleteByExample(TripPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int insert(TripPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int insertSelective(TripPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    List<TripPlan> selectByExampleWithBLOBs(TripPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    List<TripPlan> selectByExample(TripPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    TripPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TripPlan record, @Param("example") TripPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TripPlan record, @Param("example") TripPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TripPlan record, @Param("example") TripPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TripPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TripPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TripPlan record);
}