package dev.abelab.hack.dena.db.mapper.base;

import dev.abelab.hack.dena.db.entity.TripPlanTaggingExample;
import dev.abelab.hack.dena.db.entity.TripPlanTaggingKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TripPlanTaggingBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    long countByExample(TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int deleteByExample(TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TripPlanTaggingKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int insert(TripPlanTaggingKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int insertSelective(TripPlanTaggingKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    List<TripPlanTaggingKey> selectByExample(TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TripPlanTaggingKey record, @Param("example") TripPlanTaggingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trip_plan_tagging
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TripPlanTaggingKey record, @Param("example") TripPlanTaggingExample example);
}