package dev.abelab.hack.dena.db.mapper.base;

import dev.abelab.hack.dena.db.entity.UserLike;
import dev.abelab.hack.dena.db.entity.UserLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserLikeBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    long countByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int deleteByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("tripPlanId") Integer tripPlanId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int insert(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int insertSelective(UserLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    List<UserLike> selectByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserLike record, @Param("example") UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserLike record, @Param("example") UserLikeExample example);
}