package dev.abelab.hack.dena.db.mapper.base;

import dev.abelab.hack.dena.db.entity.UserLikeExample;
import dev.abelab.hack.dena.db.entity.UserLikeKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UserLikeBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    long countByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int deleteByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UserLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int insert(UserLikeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int insertSelective(UserLikeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    List<UserLikeKey> selectByExample(UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserLikeKey record, @Param("example") UserLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_like
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserLikeKey record, @Param("example") UserLikeExample example);
}