package dev.abelab.hack.dena.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class TripPlanAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip_plan_attachment.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip_plan_attachment.trip_plan_id
     *
     * @mbg.generated
     */
    private Integer tripPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip_plan_attachment.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip_plan_attachment.content
     *
     * @mbg.generated
     */
    private byte[] content;
}