package dev.abelab.hack.dena.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class TripPlanTaggingKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip_plan_tagging.trip_plan_id
     *
     * @mbg.generated
     */
    private Integer tripPlanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trip_plan_tagging.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;
}