package dev.abelab.hack.dena.db.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UserLikeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_like.trip_plan_id
     *
     * @mbg.generated
     */
    private Integer tripPlanId;
}